In [1]:
import pandas as pd
import numpy as np

#### Описание данных

В папке Dat (https://github.com/hse-ds/iad-intro-ds/blob/master/2023/homeworks/Data.zip) находится информация о студентах. Всего 10 групп студентов. Файлы делятся на две категории:
    * Students_info_i - информация о студентах из группы i
    * Students_marks_i - оценки студентов из группы i за экзамены

#### Задание 1. Соберите всю информацию о студентах в одну таблицу df. В получившейся таблице должна быть информация и оценки всех студентов из всех групп. Напечатайте несколько строк таблицы для демонстрации результата.¶

In [ ]:
import requests, zipfile, io
df1 = pd.DataFrame()
df2 = pd.DataFrame()

a = requests.get('https://github.com/hse-ds/iad-intro-ds/raw/master/2023/homeworks/Data.zip')

with open ('Data.zip', 'wb') as b:
    b.write(a.content)

with zipfile.ZipFile('Data.zip') as f:
    f.extractall()

for i in range(10):
    with open (f'Data\Students_info_{i}.csv') as table:
        df1 = pd.concat([df1, pd.read_csv(table)], ignore_index = True)

for i in range(10):
    with open (f'Data\Students_marks_{i}.csv') as table1:
        df2 = pd.concat([df2, pd.read_csv(table1)], ignore_index = True)
df = pd.merge(df1, df2, on = 'index')
df.head(7)

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,1,female,group C,some college,standard,completed,group1,69,90,88
2,2,female,group B,master's degree,standard,none,group1,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,4,male,group C,some college,standard,none,group1,76,78,75
5,5,female,group B,associate's degree,standard,none,group1,71,83,78
6,6,female,group B,some college,standard,completed,group1,88,95,92

#### Задание 2. Удалите столбец index у полученной таблицы. Напечатайте первые 10 строк таблицы.

In [ ]:
df.drop('index', axis = 1, inplace=True)
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
5,female,group B,associate's degree,standard,none,group1,71,83,78
6,female,group B,some college,standard,completed,group1,88,95,92
7,male,group B,some college,free/reduced,none,group1,40,43,39
8,male,group D,high school,free/reduced,completed,group1,64,64,67
9,female,group B,high school,free/reduced,none,group1,38,60,50

#### Задание 3. Выведите на экран размеры полученной таблицы

In [ ]:
df.shape

(1000, 9)

#### Задание 4. Выведите на экран статистические характеристики числовых столбцов таблицы (минимум, максимум, среднее значение, стандартное отклонение)

In [ ]:
df.describe().iloc[[1, 2, 3, 7]]

      math score  reading score  writing score
mean    66.08900      69.169000      68.054000
std     15.16308      14.600192      15.195657
min      0.00000      17.000000      10.000000
max    100.00000     100.000000     100.000000

#### Задание 5. Проверьте, есть ли в таблице пропущенные значения

In [ ]:
df.isnull().sum()
# пропусков нет

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
group                          0
math score                     0
reading score                  0
writing score                  0
dtype: int64

#### Задание 6. Выведите на экран средние баллы студентов по каждому предмету (math, reading, writing)

In [ ]:
df[['math score', 'reading score', 'writing score']].mean()

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

**Задание 7. Как зависят оценки от того, проходил ли студент курс для подготовки к сдаче экзамена (test preparation course)? Выведите на экран для каждого предмета в отдельности средний балл студентов, проходивших курс для подготовки к экзамену и не проходивших курс.**

In [ ]:
df.groupby('test preparation course')[['math score', 'reading score', 'writing score']].mean()
# видно, что у тех, кто не проходил курс, средний балл меньше, чем у тех, кто проходил

                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673

**Задание 8. Выведите на экран все различные значения из столбца lunch.**

In [ ]:
df.lunch.unique()

array(['standard', 'free/reduced'], dtype=object)

**Задание 9. Переименуйте колонку "parental level of education" в "education", а "test preparation course" в "test preparation" с помощью метода pandas rename**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

In [ ]:
df.rename(columns = {'parental level of education':'education', 'test preparation course':'test preparation'}, inplace=True)
df.head()

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75

**Зафиксируем минимальный балл для сдачи экзамена**

In [ ]:
passmark = 50

**Задание 10. Ответьте на вопросы:**
    * Какая доля студентов сдала экзамен по математике (passmark >= 50)?
    * Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?
    * Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?

In [ ]:
#  Какая доля студентов сдала экзамен по математике?

sdali = np.sum(df['math score'] >= passmark)
dolya = sdali / df.shape[0]
print(dolya, '- доля сдавших экзамен по математике.')

# Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?

completed_test = df.loc[df['test preparation'] == 'completed']
dolya2 = np.sum(completed_test['math score'] >= 50) / completed_test.shape[0]
print(dolya2, '- доля сдавших экзамен по математике, при этом проходивших курс подготовки.')

# Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?

female = df.loc[df['gender'] == 'female']
female_none = female.loc[female['test preparation'] == 'none']
dolya3 = np.sum(female_none['math score'] < 50) / female_none.shape[0]
print(dolya3, '- доля женщин, которые не проходили курс и не сдали экзамен')

0.865 - доля сдавших экзамен по математике.
0.9217877094972067 - доля сдавших экзамен по математике, при этом проходивших курс подготовки.
0.20958083832335328 - доля женщин, которые не проходили курс и не сдали экзамен

**Задание 11. С помощью groupby выполните задания ниже. Также выведите время выполнения каждого из заданий.**
    * Для каждой этнической группы выведите средний балл за экзамен по чтению
    * Для каждого уровня образования выведите минимальный балл за экзамен по письму

In [ ]:
%%time
# Для каждой этнической группы выведите средний балл за экзамен по чтению
print(df.groupby('race/ethnicity')['reading score'].mean())

race/ethnicity
group A    64.674157
group B    67.352632
group C    69.103448
group D    70.030534
group E    73.028571
Name: reading score, dtype: float64
CPU times: total: 0 ns
Wall time: 2.81 ms

In [ ]:
%%time
# Для каждого уровня образования выведите минимальный балл за экзамен по письму
print(df.groupby('education')['writing score'].min())

education
associate's degree    35
bachelor's degree     38
high school           15
master's degree       46
some college          19
some high school      10
Name: writing score, dtype: int64
CPU times: total: 0 ns
Wall time: 3.3 ms

**Задание 12. Выполните задание 11 с помощью циклов. Сравните время выполнения.**

In [ ]:
%%time
# Для каждой этнической группы выведите средний балл за экзамен по чтению
summ = 0
count = 0

race = df['race/ethnicity'].unique()
for value in race:
    for i in range(df.shape[0]):
        if value == df['race/ethnicity'][i]:
            summ += df['reading score'][i]
            count += 1
    print('Среднее значение в', value, '=', summ / count)
    summ = 0
    count = 0

Среднее значение в group B = 67.35263157894737
Среднее значение в group C = 69.10344827586206
Среднее значение в group A = 64.67415730337079
Среднее значение в group D = 70.03053435114504
Среднее значение в group E = 73.02857142857142
CPU times: total: 31.2 ms
Wall time: 37.3 ms

In [ ]:
%%time
# Для каждого уровня образования выведите минимальный балл за экзамен по письму
import math
minv = math.inf

edu = df['education'].unique()
for value1 in edu:
    for j in range(df.shape[0]):
        if value1 == df['education'][j]:
            if df['writing score'][j] < minv:
                minv = df['writing score'][j]
    print(f'Для уровня образования {value1} минимальный балл за экзамен по письму = {minv}')
    minv = math.inf

Для уровня образования bachelor's degree минимальный балл за экзамен по письму = 38
Для уровня образования some college минимальный балл за экзамен по письму = 19
Для уровня образования master's degree минимальный балл за экзамен по письму = 46
Для уровня образования associate's degree минимальный балл за экзамен по письму = 35
Для уровня образования high school минимальный балл за экзамен по письму = 15
Для уровня образования some high school минимальный балл за экзамен по письму = 10
CPU times: total: 31.2 ms
Wall time: 41.8 ms

*Если сравнивать время выполнения заданий разными способами, использование метода groupby в десятки раз увеличивает скорость выполнения задачи.*

**Задание 13. Выведите на экран средние баллы студентов по каждому предмету в зависимости от пола и уровня образования. То есть должно получиться количество групп, равных 2 * (число уровней образования), и для каждой такой группы выыведите средний балл по каждому из предметов.**

Это можно сделать с помощью сводных таблиц (pivot_table):

https://www.kaggle.com/kamilpolak/tutorial-how-to-use-pivot-table-in-pandas

In [ ]:
pd.pivot_table(data = df, values = ['math score', 'reading score', 'writing score'], index = ['gender', 'education'], aggfunc = 'mean')

                           math score  reading score  writing score
gender education
female associate's degree   65.250000      74.120690      74.000000
       bachelor's degree    68.349206      77.285714      78.380952
       high school          59.351064      68.202128      66.691489
       master's degree      66.500000      76.805556      77.638889
       some college         65.406780      73.550847      74.050847
       some high school     59.296703      69.109890      68.285714
male   associate's degree   70.764151      67.433962      65.405660
       bachelor's degree    70.581818      68.090909      67.654545
       high school          64.705882      61.480392      58.539216
       master's degree      74.826087      73.130435      72.608696
       some college         69.009259      64.990741      63.148148
       some high school     67.840909      64.693182      61.375000

#### Задание 14. Сколько студентов успешно сдали экзамен по математике?

Создайте новый столбец в таблице df под названием Math_PassStatus и запишите в него F, если студент не сдал экзамен по математике (балл за экзамен < passmark), и P иначе.

Посчитайте количество студентов, сдавших и не сдавших экзамен по математике.

Сделайте аналогичные шаги для экзаменов по чтению и письму.

In [ ]:
def Passed (mark, subject):
    if mark[subject] >= passmark:
        return 'P'
    else:
        return 'F'
# Математика
df['Math_PassStatus'] = df.apply(lambda x: Passed(x, 'math score'), axis = 1)
print('Количество студентов, которые сдали экзамен по математике = ', np.sum(df['Math_PassStatus'] == 'P'))
print('Не сдали экзамен по математике: ', np.sum(df['Math_PassStatus'] == 'F'))

Количество студентов, которые сдали экзамен по математике =  865
Не сдали экзамен по математике:  135

In [ ]:
# Чтение
df['Reading_PassStatus'] = df.apply(lambda x: Passed(x, 'reading score'), axis = 1)
print('Количество студентов, которые сдали экзамен по чтению = ', np.sum(df['Reading_PassStatus'] == 'P'))
print('Не сдали экзамен по чтению: ', np.sum(df['Reading_PassStatus'] == 'F'))

Количество студентов, которые сдали экзамен по чтению =  910
Не сдали экзамен по чтению:  90

In [ ]:
# Письмо
df['Writing_PassStatus'] = df.apply(lambda x: Passed(x, 'writing score'), axis = 1)
print('Количество студентов, которые сдали экзамен по письму = ', np.sum(df['Writing_PassStatus'] == 'P'))
print('Не сдали экзамен по письму: ', np.sum(df['Writing_PassStatus'] == 'F'))

df.head()

Количество студентов, которые сдали экзамен по письму =  886
Не сдали экзамен по письму:  114

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P
1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F
4,male,group C,some college,standard,none,group1,76,78,75,P,P,P

#### Задание 15. Сколько студентов успешно сдали все экзамены?

Создайте столбец OverAll_PassStatus и запишите в него для каждого студента 'F', если студент не сдал хотя бы один из трех экзаменов, а иначе 'P'.

Посчитайте количество студентов, которые сдали все экзамены.

In [ ]:
def overall(marks):
    if marks['Math_PassStatus'] == 'P' and marks['Reading_PassStatus'] == 'P' and marks['Writing_PassStatus'] == 'P':
        return 'P'
    else:
        return 'F'

df['OverAll_PassStatus'] = df.apply(overall, axis = 1)
print('Количество студентов, которые сдали все экзамены = ', np.sum(df['OverAll_PassStatus'] == 'P'))
df.head()

Количество студентов, которые сдали все экзамены =  812

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus,OverAll_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P,P
1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P,P
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F,F
4,male,group C,some college,standard,none,group1,76,78,75,P,P,P,P

#### Задание 16. Переведем баллы в оценки

### Система перевода баллов в оценки
####    больше 90 = A
####      80-90 = B
####      70-80 = C
####      60-70 = D
####      50-60 = E
####    меньше 50 = F (Fail)

Создайте вспомогательную функцию, которая будет по среднему баллу за три экзамена выставлять оценку студенту по данным выше критериям.

Создайте столбец Grade и запишите в него оценку каждого студента.

Выведите количество студентов, получивших каждую из оценок.

**В случае, если средний балл попадает на границу между оценками (т.е. равен ровно 60, 70 или 80 баллов), вы можете интерпретировать условие на своё усмотрение (т.е. можете поставить за 60 баллов оценку D, а можете - E).**

In [ ]:
def GetGrade(average_mark):
    if average_mark > 90:
        return 'A'
    elif average_mark > 80 and average_mark <= 90:
        return 'B'
    elif average_mark > 70 and average_mark <= 80:
        return 'C'
    elif average_mark > 60 and average_mark <= 70:
        return 'D'
    elif average_mark >= 50 and average_mark <= 60:
        return 'E'
    else:
        return 'F'

df['Grade'] = df[['math score', 'reading score', 'writing score']].mean(axis = 1).apply(GetGrade)

df['Grade'].value_counts() # количество студентов, получивших каждую из оценок.

Grade
D    260
C    253
E    190
B    144
F    103
A     50
Name: count, dtype: int64